styling on signup/login/navbar, favicon
MattMav21/FilmUp-Project pull request #12
Opened 2021-01-07 23:29 UTC by guipace

Styling and positioning of navbar, signup and login pages.
Small styling improvements to other areas.
Added a new favicon.

2021-01-07 23:53 UTC, edherm requested changes
Looking good! I've got just a few things for you to review before I approve this PR. Let me know when you've finished (which includes pulling main, merging that into your branch, solving merge conflicts, then pushing it back to this same branch), and I'll look it over once more.

Please do: In views/layout.pug lines 28-31: this is all repeated code! Please make a mixin to DRY this up. You just need to pass in the alt-text and github username.

Optional: This is a bigger change to all of your forms, but you should also create an input mixin to replace all of this repetitive code. If you have other issues you want to work out first, you may just want to raise an issue on the repo and put it in your kanban/project board so you can get to it eventually.

2021-01-08 02:47 UTC, guipace commented
All suggested changes have been made in addition to changing the logo on the nav bar.

2021-01-08 14:09 UTC, edherm requested changes
Please add a new mixin in utils.pug that builds the github div-links for you. Then those links would just look something like `+githubLink(memberName, githubHandle)` instead of those many repeated lines of code.

2021-01-08 14:09 UTC, edherm commented on views/layout.pug
> +        div: a(href="https://github.com/guipace"): img(class="connectWithUs-github" src="/images/githubicon.png", alt="Guilherme Pace")
Please change this (and the following three github profile links) into mixins to DRY up this section.

2021-01-08 16:08 UTC, edherm approved these changes
Nice work on these mixins!

2021-01-08 16:09 UTC, merged